os: linux

install: make get-deps

language: cpp

sudo: required

dist: trusty

before_install:
  - sudo apt-get -qq update
  - git fetch -t
  - sudo apt-get install -y python-pip
  - pip install --user travis-sphinx Sphinx alabaster 
  - export PATH=$HOME/.local/bin:$PATH

script:
  - travis-sphinx --nowarn --source=doc/Sphinx build

after_success:
  - travis-sphinx deploy
    
install:



